services:
  app:
    build:
      args:
        user: fiqi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tambakku-app
    container_name: tambakku-app-app
    restart: unless-stopped
    working_dir: /var/www/tambakku/html
    volumes:
      - ./:/var/www/tambakku/html
    networks:
      - botassist_bot-assist

  nginx:
    image: nginx:1.17-alpine
    container_name: tambakku-app-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/tambakku/html
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - botassist_bot-assist

networks:
  tambakku-app:
    driver: bridge
  botassist_bot-assist:
    external: true